name: tag
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.13.1"
          registry-url: https://registry.npmjs.org/
      - name: Publish NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish Docker
        run: |
          docker build -t withcardinal/sockets:${GITHUB_REF:10} .

          echo ${{secrets.DOCKER_TOKEN} | docker login -u thecardinal --password-stdin
          docker push withcardinal/sockets:${GITHUB_REF:10}
